---
# Add the Oracle Java (JDK) 14 Installer PPA. See https://launchpad.net/~linuxuprising/+archive/ubuntu/java
- name: Add the Oracle Java (JDK) 14 Installer PPA
  apt_repository:
    repo: ppa:linuxuprising/java
    state: present
    update_cache: true

# Accept Oracle license (JDK) 14.
- name: Accept license  (JDK) 14
  debconf:
    name: oracle-java{{ item.version }}-installer
    question: shared/accepted-oracle-license-v1-2
    answer: 'true'
    vtype: select
  loop:
    "{{ java_oracle_packages }}"
  when:
    item.version == 14

# Set Oracle Java packages to install.
- name: Set Oracle Java packages to install
  set_fact:
    java_oracle_packages_names: "{{ java_oracle_packages_names | default([]) }} + [ 'oracle-java{{ item.version }}-installer' ]"
  loop: "{{ java_oracle_packages }}"

# Install Oracle Java.
- name: Install Oracle Java
  apt:
    name: "{{ java_oracle_packages_names }}"
    state: present
    update_cache: true
    cache_valid_time: 86400
