---
# Ensure base packages are present.
- name: Install base packages
  apt:
    name:
      - software-properties-common
    state: present
    update_cache: yes
    cache_valid_time: 86400

# Install OpenJDK.
- include: install-openjdk.yml
  when:
    java_openjdk_packages

# Install Oracle Java.
- include: install-oracle.yml
  when:
    java_oracle_packages

# Configure default alternative and JAVA_HOME.
- include: configure.yml
