---
- hosts: all
  become: true

  pre_tasks:

    - name: Ensure Ansible temp directory exists
      file:
        path: /tmp/ansible
        state: directory
        mode: 0777

  roles:
    - ansible-role-java

  vars:
    ansible_python_interpreter: /usr/bin/python3
    java_oracle_packages:
      - version: 13
    java_openjdk_packages:
      - version: 11
        type: jre
      - version: 13
        type: jdk
    java_default_alternative:
      provider: openjdk
      version: 11
